import { job } from '../../../../../types/JobT'

export const dummyJobsdata: job[] = [
  {
    id: '1',
    name: 'John Smith',
    address: '123 Fake Street 123 Fake Street 123 Fake Street 123 Fake Street',
    town: '',
    postcode: 'AB1 2CD',
    cleanType: 'Front',
    price: '£2000',
    time: '1.50',
    frequency: 'Daily',
  },
  {
    id: '2',
    name: 'John Smith',
    address: '123 Fake Street',
    town: 'Aberdeen',
    postcode: 'AB1 2CD',
    cleanType: 'Front',
    price: '£20',
    time: '1.50',
    frequency: 'Daily',
  },
  {
    id: '3',
    name: 'John Smith',
    address: '123 Fake Street',
    town: 'Aberdeen',
    postcode: 'AB1 2CD',
    cleanType: 'Front Back Rear Tiles Cats Dogs',
    price: '£20',
    time: '1.75',
    frequency: 'Daily',
  },
  {
    id: '4',
    name: 'John Smith',
    address: '123 Fake Street',
    town: 'Aberdeen',
    postcode: 'AB1 2CD',
    cleanType: 'Front Back Rear Tiles Cats Dogs',
    price: '£20',
    time: '1.75',
    frequency: 'Daily',
  },
  {
    id: '5',
    name: 'John Smith',
    address: '123 Fake Street',
    town: 'Aberdeen',
    postcode: 'AB1 2CD',
    cleanType: 'Front Back Rear Tiles Cats Dogs',
    price: '£20',
    time: '1.75',
    frequency: 'Daily',
  },
  {
    id: '6',
    name: 'John Smith',
    address: '123 Fake Street',
    town: 'Aberdeen',
    postcode: 'AB1 2CD',
    cleanType: 'Front Back Rear Tiles Cats Dogs',
    price: '£20',
    time: '1.75',
    frequency: 'Monthly',
  },
  {
    id: '7',
    name: 'John Smith',
    address: '123 Fake Street',
    town: 'Aberdeen',
    postcode: 'AB1 2CD',
    cleanType: 'Front Back Rear Tiles Cats Dogs',
    price: '£20',
    time: '1.75',
    frequency: '4 Weekly',
  },
  {
    id: '8',
    name: 'John Smith',
    address: '123 Fake Street',
    town: 'Aberdeen',
    postcode: 'AB1 2CD',
    cleanType: 'Front Back Rear Tiles Cats Dogs',
    price: '£20',
    time: '1.75',
    frequency: 'Weekly',
  },
]
