import { RoundTS } from '../../../../types/Round'

export const dummyRoundData: RoundTS[] = [
  {
    id: '1',
    name: 'Wallington All',
    place: 'Wallington',
    numOfJobs: '5',
    roundTime: '3.75',
    frequency: 'Daily',
  },
  {
    id: '2',
    name: 'Sutton Shops',
    place: 'Sutton',
    numOfJobs: '5',
    roundTime: '3.75',
    frequency: 'Weekly',
  },
  {
    id: '3',
    name: 'Oprtington',
    place: 'Oprtington',
    numOfJobs: '5',
    roundTime: '3.75',
    frequency: 'Monthly',
  },
  {
    id: '4',
    name: 'Wallington All',
    place: 'Wallington',
    numOfJobs: '5',
    roundTime: '3.75',
    frequency: 'Daily',
  },
  {
    id: '5',
    name: 'Sutton Shops',
    place: 'Sutton',
    numOfJobs: '5',
    roundTime: '3.75',
    frequency: 'Daily',
  },
  {
    id: '6',
    name: 'Oprtington',
    place: 'Oprtington',
    numOfJobs: '5',
    roundTime: '3.75',
    frequency: 'Daily',
  },
  {
    id: '7',
    name: 'Wallington All',
    place: 'Wallington',
    numOfJobs: '5',
    roundTime: '3.75',
    frequency: 'Daily',
  },
  {
    id: '8',
    name: 'Sutton Shops',
    place: 'Sutton',
    numOfJobs: '5',
    roundTime: '3.75',
    frequency: 'Daily',
  },
  {
    id: '9',
    name: 'Oprtington',
    place: 'Oprtington',
    numOfJobs: '5',
    roundTime: '3.75',
    frequency: 'Daily',
  },
]
